name: "Build"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72
        with:
          # explicitly enable sandbox
          extra_nix_config: sandbox = true

      - run: nix build

      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: result/
